server:
  port: 8201
  
spring:
  application:
    name:  microservicecloud-config-client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/
 
